### ISSUE TITLE
contrib: detailed docs for ruby newbs

### ISSUE THREAD

**Issue by holtzermann17** [loomio/loomio#455]
On Ubuntu 12.04:

```
sudo apt-get install postgresql-8.4 postgresql-server-dev-8.4
```

But don't do this:

```
sudo apt-get install ruby1.9.3
sudo apt-get install rails
sudo apt-get install ruby-rvm
```

[You will run into trouble if you do that](http://stackoverflow.com/a/9056395/497756).

> You'll have to delete various programs from `/usr/bin/` (like `bundle` and `gem`) if you "accidentally" went through an install based on Ubuntu before doing it the right way.

Rather:

```
sudo \curl -L get.rvm.io | bash -s -- --auto-dotfiles --ruby --rails
```

See the link above for details.
## You also need to do this:

```
sudo gem install bundler
bundle install
bundle install --deployment
```

```
sudo -u postgres psql postgres
postgres=# \password
Enter new password: xxxx
Enter it again: xxxx
```

Edit `config/database.yml`, provide

```
development:
  adapter: postgresql
  database: loomio_development
  username: postgres
  password: xxxx

test:
  adapter: postgresql
  database: loomio_test
  username: postgres
  password: xxxx
```

Edit `/etc/postgresql/8.4/main/pg_hba.conf` and provide:

```
# Database administrative login by Unix domain socket
local   all             postgres                                md5
```

```
sudo gem install foreman
```

Now follow the instructions in the loomio README, except you also have to run:

```
console/script/console
```

(However, I'm still not able to create a user, see #454.)
